Add HentPasientliste send-in request
navikt/ebxml-processor pull request #40
Opened 2024-09-20 13:48 UTC by GardOS

Includes logging- and structural improvements

2024-09-20 14:35 UTC, GardOS commented
Plundret litt på hvordan jeg skulle lage tester for dette her. Jeg kunne kjørt opp noen enkle unit tester og hive inn litt mocks høyre og venstre, men da får jeg ikke helt testen roten av det som er interessant. Jeg leste litt på det og det finnes noen interessante måter å få testet hele løpet gjennom ktor som jeg har lyst å utforske. Branchen her har fått litt lang levetid og overlapper nå med andre utviklere sitt arbeid, så jeg tenker jeg tar det isolert.

2024-09-20 14:40 UTC, ivanskodje commented on ebms-send-in/src/main/kotlin/no/nav/emottak/ebms/App.kt
> +                }
Kan være lurt å spesifisere at dette er innkommende request object som feiler mappingen

2024-09-20 14:42 UTC, ivanskodje commented on ebms-send-in/src/main/kotlin/no/nav/emottak/ebms/App.kt
> +                                throw NotImplementedError("Service: ${request.addressing.service} is not implemented")
Hva blir konsekvens ved å kaste exception, i stedet for å bare logge direkte og gjøre ingenting?

2024-09-20 14:44 UTC, ivanskodje commented on ebms-send-in/src/main/kotlin/no/nav/emottak/fellesformat/FellesFormatWrapper.kt
> +        it.ediLoggId = sendInRequest.messageId
Jeg er ikke sikker på hvordan mottak håndterer dette, og jeg vet ikke om dette er i det hele tatt mulig, men kan det hende at messageId er null? Hvis den kan være null i en eller annen flyt, lurer jeg på om det kan være lurt å sende en empty string i stedet for null som kommer i XML som teksten null. Jeg vet ikke da, bare lufter tanker :sweat_smile:

2024-09-20 14:47 UTC, ivanskodje commented on ebms-send-in/src/main/kotlin/no/nav/emottak/frikort/FrikortClient.kt
> +        log.info("Sending in frikortsporring request with body: " + FellesFormatXmlMarshaller.marshal(fellesformat))
Veldig fine logger å ha! :+1:

2024-09-20 14:49 UTC, ivanskodje commented on ebms-send-in/src/main/kotlin/no/nav/emottak/pasientliste/PasientlisteClient.kt
> +        }
Hmm, med tanke på hvor ofte vi nå bruker !isProdEnv sjekker før logging, lurer jeg på om det kan være verdt å lage en log extension metode på loggeren som vi kan bruke som bare logger til stage uten at vi trenger å legge inn sjekker manuelt  :brain:

2024-09-20 14:53 UTC, ivanskodje commented on ebms-send-in/src/main/kotlin/no/nav/emottak/pasientliste/PasientlisteClient.kt
> +        }
`log.q1("hello world")` ?

2024-09-20 15:22 UTC, alpet requested changes
Logging bør ikke skje basert på miljø.

2024-09-20 15:30 UTC, alpet reviewed
Logging bør ikke skje basert på miljø.

2024-09-20 15:31 UTC, alpet reviewed
Logging bør ikke skje basert på miljø.

2024-09-20 15:37 UTC, alpet reviewed
test

2024-09-20 15:39 UTC, alpet reviewed
test

2024-09-20 15:40 UTC, alpet reviewed
test

2024-09-20 15:41 UTC, alpet approved these changes

2024-09-20 15:41 UTC, alpet reviewed
test

2024-09-23 12:20 UTC, alpet approved these changes

2024-09-23 12:28 UTC, merged