Liten refactor med historikk forsok nummer to
navikt/ebxml-processor pull request #48
Opened 2024-10-10 08:49 UTC by ivanskodje

Fungerer det nå?

2024-10-10 12:50 UTC, alpet requested changes

2024-10-10 12:50 UTC, alpet commented on ebms-provider/src/main/kotlin/no/nav/emottak/ebms/ebxml/ApplicationCallExt.kt
> +suspend fun ApplicationCall.handleMultipartRelated(): EbMSDocument {
Den blir private da hvis du separerer dem sånn.

2024-10-10 12:50 UTC, alpet commented on ebms-provider/src/main/kotlin/no/nav/emottak/ebms/ebxml/ApplicationCallExt.kt
> +suspend fun ApplicationCall.handleTextXml(): EbMSDocument {
også private

2024-10-10 12:50 UTC, alpet commented on ebms-provider/src/main/kotlin/no/nav/emottak/ebms/ebxml/ApplicationCallExt.kt
> +suspend fun ApplicationCall.handleMultipartRelated(): EbMSDocument {
Bedre å ha fuksjonel navn som f.x. handlePayloadMessage()

2024-10-10 12:50 UTC, alpet commented on ebms-provider/src/main/kotlin/no/nav/emottak/ebms/ebxml/ApplicationCallExt.kt
> +suspend fun ApplicationCall.handleTextXml(): EbMSDocument {
Jeg vet ikke hva er riktin navn for denne methoden. Kan stå sånn for øyeblikket.

2024-10-11 04:08 UTC, ivanskodje commented on ebms-provider/src/main/kotlin/no/nav/emottak/ebms/ebxml/ApplicationCallExt.kt
> +suspend fun ApplicationCall.handleMultipartRelated(): EbMSDocument {
Snakker vi om `handleMultipartRelated`? Fordi begge er funksjonelle navn i denne sammenhengen, utenom at PayloadMessage ikke beskriver godt hvilken use case vi håndterer

Skal uansett refaktorere litt til, jeg er ikke glad at vi knytter ebmsDocument logikk med ApplicationCall extensions, siden det egentlig ikke har noe med ApplicationCall å gjøre (burde ikke være global)

2024-10-11 08:02 UTC, alpet commented on ebms-provider/src/main/kotlin/no/nav/emottak/ebms/ebxml/ApplicationCallExt.kt
> +suspend fun ApplicationCall.handleMultipartRelated(): EbMSDocument {
Det beskriver godt nok situasjonen. Du enten har en message med Payload (Fagmelding) eller du har et slags trasport kvitering. Begge kan vare multipart/related men bare 1 vil ha payload.

2024-10-11 08:56 UTC, ivanskodje commented
Lekte litt med å ta ut extension metodene, men det ble mer bry enn det er verdt for øyeblikket. Hvis noen får en bedre idé i fremtiden er det bare å refaktorere igjen. Lar denne stå slik som den er, og hvis andre føler for å refaktorere videre er det bare å hoppe på det

2024-10-11 09:25 UTC, alpet approved these changes

2024-10-11 09:30 UTC, merged