Lagt til en enkel juridisk logg klient
navikt/ebxml-processor pull request #50
Opened 2024-10-15 13:08 UTC by OleksandrChmyrNAV

2024-10-16 10:14 UTC, RettIProd commented on ebms-payload/src/main/kotlin/no/nav/emottak/payload/juridisklogg/JuridiskLoggService.kt
> +        val response = runBlocking {
Foreslår å bruke suspend + withcontext(Dispatchers.IO)

2024-10-16 12:12 UTC, RettIProd approved these changes
- [x] Kjørt ktlintFormat
Ser bra ut, bare husk å kjøre ktlintFormat sånn at det bygger.

2024-10-17 04:49 UTC, ivanskodje requested changes

2024-10-17 04:49 UTC, ivanskodje commented on ebms-payload/src/main/kotlin/no/nav/emottak/payload/Processor.kt
> +                // if (processConfig.juridiskLogg) {
Hvorfor beholder vi denne utkommenterte koden?

2024-10-17 04:51 UTC, ivanskodje commented on ebms-payload/src/main/kotlin/no/nav/emottak/payload/juridisklogg/JuridiskLoggService.kt
> +    // bare for feilsøking
Unødvendig kommentar, tror egentlig at alt bruk av  debug logging blir brukt til feilsøking og tracing av flyt :sweat_smile:

2024-10-17 06:57 UTC, OleksandrChmyrNAV commented on ebms-payload/src/main/kotlin/no/nav/emottak/payload/Processor.kt
> +                // if (processConfig.juridiskLogg) {
Ingen RSA i databasen har `juridisk_logg=true.` Ny koden vil aldri kjøres hvis betingelsen er ukommentert.

2024-10-22 05:23 UTC, ivanskodje commented on ebms-payload/src/main/kotlin/no/nav/emottak/payload/Processor.kt
> +                // if (processConfig.juridiskLogg) {
Så dette er en midertidlig hack?

2024-10-22 06:16 UTC, OleksandrChmyrNAV commented on ebms-payload/src/main/kotlin/no/nav/emottak/payload/Processor.kt
> +                // if (processConfig.juridiskLogg) {
Ja, akkurat det.

2024-11-07 12:18 UTC, OleksandrChmyrNAV commented on ebms-payload/src/main/kotlin/no/nav/emottak/payload/juridisklogg/JuridiskLoggService.kt
> +    // bare for feilsøking
Enig :)

2024-11-07 12:22 UTC, OleksandrChmyrNAV commented on ebms-payload/src/main/kotlin/no/nav/emottak/payload/Processor.kt
> +                // if (processConfig.juridiskLogg) {
Betingelsen er kommentert inn.

2024-11-08 09:01 UTC, ivanskodje approved these changes

2024-11-08 09:13 UTC, merged